### PR TITLE
Added mercantile automata cores

### PR DESCRIPTION
**Pull request by grace5532**
Features implemented:
	- Added "Mercantile automata core"
		* receives detailed villager trade information when using "look" and "scan" (requires the "merchantData" data enricher from the Peripheralium pull request)
		* has a "trade" function
			* [vertical direction], first_cost_slot, [second_cost_slot]
			* returns: number of items received from trade
			* places results in selected slot or first available
Notes:
	- I didn't add any extra features for the higher core tiers, maybe they should be able to trade with any villager in their interaction radius? (right now you can only trade with a villager directly in front, above, or below)

### CODE REVIEW

**Comment by SirEdvin** [comment]
Thanks for you code, sorry for delay with replay. I will review it next week

**Comment by grace5532** [comment]
Oh no worries, I hope all is well. Let me know if there's anything you need when you're doing the review

**Comment by SirEdvin** [comment]
So, thanks for code, I am going to merge it.
There are some things, that I would probably change:
- Receipt shouldn't consume Iron Golem .... probably. I will check my notes on this question :)
- Probably some changes to API, I am not sure, as usual. 
Anyway, thanks for your contribution.

**Comment by SirEdvin** [comment]
Oh, as usual, I changed a lot. 

Trading will also work with wandering trader, ~~will provide XP~~, you will have ability to hint trade that you want to make (there is can be several trades with emerald + book, for example) and something like this.

**Comment by grace5532** [comment]
Your changes make sense, thanks for reviewing it! I don't remember why I thought it was a good idea to chose the trade automatically, but hinting is better. Thanks again!

**Comment by SirEdvin** [comment]
It will try to trade automatically, but if it founds several candidates, hint will reqbe be requested

**Comment by SirEdvin** [comment]
Btw, this feature is relesed in version 0.5.3 for both 1.18 and 1.19.2

**Comment by SirEdvin** [comment]
I will add documentation today or tommorow, but in general it look like this:

`trade(hint?: int, direction?: Direction)`. Item to trade should be in selected slot and second item should be next to it if required. 

Why this design? This decent to ComputerCraft `craft` function which I found pretty nice to use

**Comment by SirEdvin** [comment]
And [documentation](https://docs.siredvin.site/Turtlematic/automata/mercantile/) is also added

**Comment by grace5532** [comment]
That makes sense, also, the documentation looks great, and allowing starbound cores to restock is a great idea! I’m sure you don’t need my approval, but still, this is very exciting

**Pull request merged**
